### ISSUE TITLE
Unable to install transmart - Target "clean dist deploy jboss_pre_deployment_setup" does not exist in the project "i2b2Common". 

### ISSUE THREAD

**Issue by philippeluickx** [thehyve/transmartAppInstaller#2]
Dear,

I am trying to install transmart and am stuck at
Target "clean dist deploy jboss_pre_deployment_setup" does not exist in the project "i2b2Common". 
Thanks for pointing out what to do!

Executing /usr/bin/ant '-q' 'load_workdata'
     [exec]      [echo] -----------------Loading Workdata module-----------------
------ i2b2Demodata
i2b2Coreserver:
Executing /usr/bin/ant 'clean dist deploy jboss_pre_deployment_setup'
     [exec] Buildfile: /opt/transmart/build/i2b2_1.6_postgres/coreserver/src/edu.harvard.i2b2.common/build.xml
     [exec] BUILD FAILED
     [exec] Target "clean dist deploy jboss_pre_deployment_setup" does not exist in the project "i2b2Common". 
     [exec] Total time: 0 seconds
Exception was raised: exec returned: 1

Full output:

Executing /usr/bin/psql '-U' 'postgres' '-d' 'postgres' '-c' 'select 1'
     [exec] psql: FATAL:  Peer authentication failed for user "postgres"
     [exec] Result: 2
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'postgres' '-c' 'select 1'
     [exec]  ?column? 
     [exec] ----------
     [exec]         1
     [exec](1 row)
default:
clean:
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'postgres' '-c' 'drop database transmart'
     [exec] DROP DATABASE
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'postgres' '-c' 'reassign owned by biomart, biomart_user, deapp, i2b2demodata, i2b2hive, i2b2metadata, i2b2pm, i2b2workdata, searchapp to postgres;'
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'postgres' '-c' 'drop role biomart'
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'postgres' '-c' 'drop role biomart_user'
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'postgres' '-c' 'drop role deapp'
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'postgres' '-c' 'drop role i2b2demodata'
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'postgres' '-c' 'drop role i2b2hive'
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'postgres' '-c' 'drop role i2b2metadata'
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'postgres' '-c' 'drop role i2b2pm'
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'postgres' '-c' 'drop role i2b2workdata'
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'postgres' '-c' 'drop role searchapp'
   [delete] Deleting directory /opt/transmart/build
------ clean
install:
Executing /usr/bin/git 'clone' 'git://github.com/transmart/transmartApp-DB.git' '/opt/transmart/build/transmartApp-DB' '--single-branch' '-b' 'postgresMigrate'
     [exec] to '/opt/transmart/build/transmartApp-DB'...
createTransmartDB:
About to execute SQL script /tmp/createdb645770052793739390.sql
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-f' '/tmp/createdb645770052793739390.sql' '-d' 'postgres' '--quiet'
------ createTransmartDB
ensureTablespaces:
Ensure /opt/transmart/db tablespace location directories are present
------ ensureTablespaces
populateTransmartDB:
About to execute SQL script /opt/transmart/build/transmartApp-DB/postgresql/tablespaces.sql
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-f' '/opt/transmart/build/transmartApp-DB/postgresql/tablespaces.sql' '-d' 'transmart' '--quiet'
About to execute SQL script /opt/transmart/build/transmartApp-DB/postgresql/biomart_user.sql
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-f' '/opt/transmart/build/transmartApp-DB/postgresql/biomart_user.sql' '-d' 'transmart' '--quiet'
About to execute SQL script /opt/transmart/build/transmartApp-DB/postgresql/searchapp/prerequisites.sql
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-f' '/opt/transmart/build/transmartApp-DB/postgresql/searchapp/prerequisites.sql' '-d' 'transmart' '--quiet'
About to execute SQL script /opt/transmart/build/transmartApp-DB/postgresql/biomart/prerequisites.sql
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-f' '/opt/transmart/build/transmartApp-DB/postgresql/biomart/prerequisites.sql' '-d' 'transmart' '--quiet'
About to execute SQL script /opt/transmart/build/transmartApp-DB/postgresql/deapp/prerequisites.sql
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-f' '/opt/transmart/build/transmartApp-DB/postgresql/deapp/prerequisites.sql' '-d' 'transmart' '--quiet'
About to execute SQL script /opt/transmart/build/transmartApp-DB/postgresql/i2b2_prerequisites.sql
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-f' '/opt/transmart/build/transmartApp-DB/postgresql/i2b2_prerequisites.sql' '-d' 'transmart' '--quiet'
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-d' 'transmart' '-c' 'drop schema if exists biomart, deapp, searchapp, i2b2demodata, i2b2hive, i2b2metadata, i2b2pm, i2b2workdata cascade;'
     [exec] DROP SCHEMA
Executing sudo '-u' 'postgres' '/usr/bin/pg_restore' '-U' 'postgres' '-d' 'transmart' '/opt/transmart/build/dump_f8d151a_db'
     [exec] WARNING:  column "correl_type" has type "unknown"
     [exec] DETAIL:  Proceeding with relation creation anyway.
------ populateTransmartDB
verifyTransmartDB:
verifySEARCHAPPdata:
About to execute SQL script /opt/transmart/build/transmartApp-DB/postgresql/searchapp/data/check_counts.sql
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-f' '/opt/transmart/build/transmartApp-DB/postgresql/searchapp/data/check_counts.sql' '-d' 'transmart'
     [exec] | 105844
     [exec]  SEARCH_KEYWORD                |  42114
     [exec]  SEARCH_REQUEST_MAP            |     17
     [exec]  PLUGIN_MODULE                 |     11
     [exec]  SEARCH_ROLE_AUTH_USER         |     11
     [exec]  SEARCH_AUTH_PRINCIPAL         |      6
     [exec]  SEARCH_AUTH_USER              |      5
     [exec]  SEARCH_ROLE                   |      5
     [exec]  SEARCH_GENE_SIG_FILE_SCHEMA   |      3
     [exec]  SEARCH_SEC_ACCESS_LEVEL       |      3
     [exec]  SEARCH_AUTH_GROUP             |      1
     [exec]  PLUGIN                        |      1
     [exec]  SEARCH_AUTH_GROUP_MEMBER      |      0
     [exec]  SEARCH_SECURE_OBJECT_PATH     |      0
     [exec]  SEARCH_GENE_SIGNATURE_ITEM    |      0
     [exec]  SEARCH_BIO_MKR_CORREL_FAST_MV |      0
     [exec]  SEARCH_CUSTOM_FILTER_ITEM     |      0
     [exec]  SEARCH_APP_ACCESS_LOG         |      0
     [exec]  SEARCH_CUSTOM_FILTER          |      0
     [exec]  SEARCH_SECURE_OBJECT          |      0
     [exec]  SEARCH_AUTH_USER_SEC_ACCESS   |      0
     [exec]  SEARCH_AUTH_SEC_OBJECT_ACCESS |      0
     [exec]  SEARCH_GENE_SIGNATURE         |      0
     [exec](23 rows)
checking: SEARCH_KEYWORD_TERM | 105844 = 105844 ...  OK!
checking: SEARCH_KEYWORD | 42114 = 42114 ...     OK!
checking: SEARCH_REQUEST_MAP | 17 = 17 ...   OK!
checking: PLUGIN_MODULE | 11 = 11 ...    OK!
------ verifySEARCHAPPdata
verifyDEAPPdata:
About to execute SQL script /opt/transmart/build/transmartApp-DB/postgresql/deapp/data/check_counts.sql
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-f' '/opt/transmart/build/transmartApp-DB/postgresql/deapp/data/check_counts.sql' '-d' 'transmart'
     [exec]  rows)
checking: DE_SUBJECT_MICROARRAY_DATA | 54400 = 54400 ...     OK!
checking: DE_MRNA_ANNOTATION | 5440 = 5440 ...   OK!
checking: DE_SUBJECT_SAMPLE_MAPPING | 10 = 10 ...    OK!
checking: DE_SAVED_COMPARISON | 5 = 5 ...    OK!
------ verifyDEAPPdata
verifyBIOMARTdata:
About to execute SQL script /opt/transmart/build/transmartApp-DB/postgresql/biomart/data/check_counts.sql
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-f' '/opt/transmart/build/transmartApp-DB/postgresql/biomart/data/check_counts.sql' '-d' 'transmart'
     [exec]      0
     [exec]  BIO_LIT_REF_DATA            |      0
     [exec]  BIO_CLINICAL_TRIAL_DESIGN   |      0
     [exec]  BIO_LIT_AMD_DATA            |      0
     [exec]  CTD_DRUG_INHIB              |      0
     [exec]  BIO_COMPOUND                |      0
     [exec]  BIO_ASY_DATA_STATS_ALL      |      0
     [exec]  CTD2_INHIB_DETAILS          |      0
     [exec]  CTD_FULL                    |      0
     [exec]  CTD_DISEASE                 |      0
     [exec]  BIO_ASSAY_DATA              |      0
     [exec]  BIO_CURATION_DATASET        |      0
     [exec]  CTD2_STUDY                  |      0
     [exec]  BIO_PATIENT_EVENT           |      0
     [exec]  CTD2_TRIAL_DETAILS          |      0
     [exec]  BIO_CURATED_DATA            |      0
     [exec]  BIO_CLINC_TRIAL_TIME_PT     |      0
     [exec]  BIO_DATA_COMPOUND           |      0
     [exec]  BIO_CGDCP_DATA              |      0
     [exec]  BIO_ASSAY_DATA_STATS        |      0
     [exec]  BIO_CELL_LINE               |      0
     [exec]  CTD_SEC_ENDPTS              |      0
     [exec]  BIO_STATS_EXP_MARKER        |      0
     [exec]  BIO_CLINC_TRIAL_ATTR        |      0
     [exec]  BIO_DATA_TAXONOMY           |      0
     [exec]  BIO_SUBJECT                 |      0
     [exec]  BIO_DATA_LITERATURE         |      0
     [exec]  bio_lit_int_model_mv        |      0
     [exec]  BIO_LIT_SUM_DATA            |      0
     [exec]  BIO_LIT_PE_DATA             |      0
     [exec]  BIO_DATA_CORREL_DESCR       |      0
     [exec]  CTD_ALLOWED_MEDS_TREATMENT  |      0
     [exec]  CTD_STUDY                   |      0
     [exec]  BIO_LIT_INH_DATA            |      0
     [exec]  CTD2_CLIN_INHIB_EFFECT      |      0
     [exec]  BIO_LIT_ALT_DATA            |      0
     [exec]  BIO_PATIENT                 |      0
     [exec]  CTD_INCLUSION_CRITERIA      |      0
     [exec]  BIO_DATA_ATTRIBUTE          |      0
     [exec]  BIO_LIT_INT_DATA            |      0
     [exec]  CTD_PRIMARY_ENDPTS          |      0
     [exec]  BIO_LIT_MODEL_DATA          |      0
     [exec]  BIO_ASSAY                   |      0
     [exec]  CTD2_DISEASE                |      0
     [exec]  BIO_DATA_CORRELATION        |      0
     [exec]  BIO_SAMPLE                  |      0
     [exec]  CTD_BIOMARKER               |      0
     [exec]  BIO_CLINICAL_TRIAL          |      0
     [exec]  BIO_ASY_ANALYSIS_DATASET    |      0
     [exec](73 rows)
checking: BIO_ASSAY_FEATURE_GROUP | 237002 = 237002 ...  OK!
checking: BIO_ASSAY_ANALYSIS_DATA | 184538 = 184538 ...  OK!
checking: BIO_DATA_EXT_CODE | 134965 = 134965 ...    OK!
checking: BIO_DATA_UID | 126764 = 126764 ...     OK!
------ verifyBIOMARTdata
------ verifyTransmartDB
downloadI2B2:
      [get] Getting: http://transmartproject.org/wiki/download/attachments/30441474/jboss-4.2.2.GA.tar.gz?version=1&modificationDate=1335242608000
      [get] To: /opt/transmart/build/jboss.tar.gz
    [untar] Expanding: /opt/transmart/build/jboss.tar.gz into /opt/transmart/build
     [move] Moving 1208 files to /opt/transmart
      [get] Getting: http://jdbc.postgresql.org/download/postgresql-9.2-1002.jdbc4.jar
      [get] To: /opt/transmart/jboss-4.2.2.GA/server/default/lib/postgresql-9.2-1002.jdbc4.jar
------ downloadI2B2
executeI2b2ImportScripts:
About to execute SQL script /opt/transmart/build/transmartApp-DB/postgresql/i2b2_prerequisites.sql
Executing sudo '-u' 'postgres' '/usr/bin/psql' '-U' 'postgres' '-f' '/opt/transmart/build/transmartApp-DB/postgresql/i2b2_prerequisites.sql' '-d' 'transmart' '--quiet'
Executing /usr/bin/git 'clone' 'git://github.com/transmart/i2b2_1.6_Postgres.git' '/opt/transmart/build/i2b2_1.6_postgres'
     [exec] Cloning into '/opt/transmart/build/i2b2_1.6_postgres'...
i2b2Demodata:
Executing /usr/bin/ant 'setup_db_properties'
     [exec] a/src/src/edu.harvard.i2b2.data/Release_1-6/NewInstall/build.xml
     [exec] setup_db_properties:
     [exec]      [echo] -----------Setting property values in db.properties-----------
     [exec] BUILD SUCCESSFUL
     [exec] Total time: 0 seconds
Executing /usr/bin/ant '-q' 'load_pmdata'
     [exec]      [echo] -----------------Loading Project Management data-----------------
Executing /usr/bin/ant '-q' 'load_hivedata'
     [exec]      [echo] -----------------Loading Hive data-----------------
     [exec] BUILD SUCCESSFUL
     [exec] Total time: 1 second
Executing /usr/bin/ant '-q' 'load_demodata'
     [exec]      [echo] -----------------Loading Demodata module-----------------
     [exec]      [echo] Loading demodata -- may take a while; over 10 min
     [exec] BUILD SUCCESSFUL
     [exec] Total time: 2 minutes 10 seconds
Executing /usr/bin/ant '-q' 'load_metadata'
     [exec]      [echo] -----------------Loading Metadata module-----------------
     [exec]      [echo] Loading metadata -- may take a while; over 10 min
     [exec] BUILD SUCCESSFUL
     [exec] Total time: 1 minute 54 seconds
Executing /usr/bin/ant '-q' 'load_workdata'
     [exec]      [echo] -----------------Loading Workdata module-----------------
------ i2b2Demodata
i2b2Coreserver:
Executing /usr/bin/ant 'clean dist deploy jboss_pre_deployment_setup'
     [exec] Buildfile: /opt/transmart/build/i2b2_1.6_postgres/coreserver/src/edu.harvard.i2b2.common/build.xml
     [exec] BUILD FAILED
     [exec] Target "clean dist deploy jboss_pre_deployment_setup" does not exist in the project "i2b2Common". 
     [exec] Total time: 0 seconds
Exception was raised: exec returned: 1

**Comment by cataphract** [comment]
That's been fixed for some days now. Fetch the latest version.

**Comment by philippeluickx** [comment]
Fantastic, confirm it works now!
